import { selectModel } from "./selectModel";
import { executeChainStream } from "./executeChain";
import { appendChunk, readChunksAfter, type LoggedChunk } from "../storage/chunkLog";

export type TaskStatus = "running" | "completed" | "failed";

type Subscriber = {
  id: number;
  push: (chunk: LoggedChunk) => void;
  close: (err?: Error) => void;
};

type ActiveTask = {
  taskContextId: string;
  status: TaskStatus;
  error?: string;
  usedModel?: string;
  // Monotonic id for chunks. 0 is "no chunks yet" — first chunk is 1.
  nextChunkId: number;
  subscribers: Set<Subscriber>;
  // Recent chunks held in-memory so a subscriber that arrives just after a
  // chunk was emitted can replay from RAM instead of re-reading disk.
  recentChunks: LoggedChunk[];
  startedAt: number;
  endedAt?: number;
};

const RECENT_BUFFER_SIZE = 256;

// taskContextId → ActiveTask. Tasks stay here while running; on completion we
// keep them for a grace period so late reconnections still find them.
const activeTasks = new Map<string, ActiveTask>();

const COMPLETED_RETENTION_MS = Number(
  process.env.TASK_BROKER_COMPLETED_RETENTION_MS ?? 60_000
);

function pruneTask(taskId: string): void {
  setTimeout(() => {
    const task = activeTasks.get(taskId);
    if (task && task.status !== "running" && task.subscribers.size === 0) {
      activeTasks.delete(taskId);
    }
  }, COMPLETED_RETENTION_MS).unref();
}

export type StartTaskOptions = {
  messages: any[];
  decision: ReturnType<typeof selectModel>;
  taskType: string;
  previousRequestId?: string;
};

export type StartTaskResult = {
  taskContextId: string;
};

/**
 * Kicks off a task. The task runs in the background until completion or
 * failure regardless of whether anyone is currently subscribed. Subscribers
 * attach via `subscribe()`.
 *
 * The taskContextId is generated by executeChainStream the first time it
 * yields a chunk that carries it, which means we need to peek at the first
 * chunk before resolving. To keep the API simple, we instead pre-allocate
 * a placeholder and patch it once the real id is observed. Callers who want
 * the real id should grab it off the first chunk they receive.
 */
export function startTask(options: StartTaskOptions): {
  taskContextIdPromise: Promise<string>;
} {
  // We don't know the real taskContextId until the first chunk arrives.
  // Resolve the promise as soon as we see it.
  let resolveId: (id: string) => void;
  let rejectId: (err: Error) => void;
  const taskContextIdPromise = new Promise<string>((resolve, reject) => {
    resolveId = resolve;
    rejectId = reject;
  });

  // Run the chain in the background.
  void (async () => {
    let task: ActiveTask | null = null;

    try {
      const stream = executeChainStream(
        options.decision.fallbackChain,
        options.messages,
        options.taskType,
        { previousRequestId: options.previousRequestId }
      );

      for await (const chunk of stream) {
        // First time we see the taskContextId, register the task and resolve.
        if (chunk.taskContextId && !task) {
          task = {
            taskContextId: chunk.taskContextId,
            status: "running",
            nextChunkId: 1,
            subscribers: new Set(),
            recentChunks: [],
            startedAt: Date.now()
          };
          activeTasks.set(chunk.taskContextId, task);
          resolveId(chunk.taskContextId);
        }

        if (!task) {
          // Defensive: chain didn't include taskContextId on the first chunk.
          // This shouldn't happen with the current implementation but we
          // don't want to silently drop output.
          continue;
        }

        if (chunk.usedModel) {
          task.usedModel = chunk.usedModel;
        }

        // Skip purely informational thinking chunks from the broker's own
        // perspective — they're already logged in TaskContext events.
        // But heartbeats *do* matter: they keep idle subscribers alive.
        const isHeartbeat =
          chunk.kind === "thinking" &&
          typeof chunk.raw === "object" &&
          chunk.raw !== null &&
          (chunk.raw as { heartbeat?: boolean }).heartbeat === true;

        const isContent = !!chunk.content;

        if (!isContent && !isHeartbeat) {
          // Non-content, non-heartbeat thinking — skip, already noted upstream.
          continue;
        }

        const logged: LoggedChunk = {
          chunkId: task.nextChunkId++,
          timestamp: Date.now(),
          kind: isHeartbeat ? "heartbeat" : "content",
          content: chunk.content,
          usedModel: chunk.usedModel,
          meta: isHeartbeat ? { heartbeat: true } : undefined
        };

        // Persist before broadcasting so a crash mid-broadcast still leaves
        // the chunk recoverable on disk.
        await appendChunk(task.taskContextId, logged);

        task.recentChunks.push(logged);
        if (task.recentChunks.length > RECENT_BUFFER_SIZE) {
          task.recentChunks.shift();
        }

        for (const sub of task.subscribers) {
          try {
            sub.push(logged);
          } catch {
            // Subscriber's push may throw if its sink is closed — let close()
            // handle it on the next iteration.
          }
        }
      }

      if (task) {
        task.status = "completed";
        task.endedAt = Date.now();
        const completionChunk: LoggedChunk = {
          chunkId: task.nextChunkId++,
          timestamp: Date.now(),
          kind: "completed",
          content: "",
          usedModel: task.usedModel
        };
        await appendChunk(task.taskContextId, completionChunk);
        for (const sub of task.subscribers) {
          try {
            sub.push(completionChunk);
          } catch {
            // ignore
          }
          try {
            sub.close();
          } catch {
            // ignore
          }
        }
        task.subscribers.clear();
        pruneTask(task.taskContextId);
      } else {
        rejectId(new Error("Task completed without ever yielding a taskContextId"));
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error("Task broker: chain failed", message);
      if (task) {
        task.status = "failed";
        task.error = message;
        task.endedAt = Date.now();
        const errorChunk: LoggedChunk = {
          chunkId: task.nextChunkId++,
          timestamp: Date.now(),
          kind: "error",
          content: "",
          meta: { error: message }
        };
        try {
          await appendChunk(task.taskContextId, errorChunk);
        } catch {
          // ignore log failures during failure handling
        }
        for (const sub of task.subscribers) {
          try {
            sub.push(errorChunk);
          } catch {
            // ignore
          }
          try {
            sub.close(err instanceof Error ? err : new Error(message));
          } catch {
            // ignore
          }
        }
        task.subscribers.clear();
        pruneTask(task.taskContextId);
      } else {
        rejectId(err instanceof Error ? err : new Error(message));
      }
    }
  })();

  return { taskContextIdPromise };
}

export type SubscribeOptions = {
  taskContextId: string;
  afterChunkId: number;
  signal?: AbortSignal;
};

/**
 * Subscribe to a task's chunks starting after `afterChunkId`. Replays from
 * disk first, then attaches live for any in-flight task. If the task is
 * already finished and out of retention, replays from disk only.
 */
export async function* subscribe(
  options: SubscribeOptions
): AsyncIterable<LoggedChunk> {
  const { taskContextId, afterChunkId } = options;

  // Phase 1: replay from disk. This catches everything emitted up to "now",
  // including chunks the live task has already broadcast. Live chunks that
  // arrive during replay are buffered in the task's in-memory queue and
  // delivered in phase 2.
  let lastReplayedChunkId = afterChunkId;
  for await (const chunk of readChunksAfter(taskContextId, afterChunkId)) {
    if (options.signal?.aborted) return;
    lastReplayedChunkId = chunk.chunkId;
    yield chunk;
    if (chunk.kind === "completed" || chunk.kind === "error") {
      return;
    }
  }

  // Phase 2: attach live if the task is still running.
  const task = activeTasks.get(taskContextId);
  if (!task || task.status !== "running") {
    return;
  }

  // Buffer + condvar for live chunks.
  const buffer: LoggedChunk[] = [];
  let notify: (() => void) | null = null;
  let closed = false;
  let closeError: Error | undefined;

  const subscriber: Subscriber = {
    id: Math.random(),
    push: (chunk) => {
      if (closed) return;
      // Skip chunks we already replayed from disk.
      if (chunk.chunkId <= lastReplayedChunkId) return;
      buffer.push(chunk);
      notify?.();
    },
    close: (err) => {
      closed = true;
      closeError = err;
      notify?.();
    }
  };

  task.subscribers.add(subscriber);

  // Replay any chunks the task pushed to its recent buffer between phase 1
  // ending and us attaching. recentChunks may already include some we
  // replayed from disk; the chunkId comparison filters them out.
  for (const chunk of task.recentChunks) {
    subscriber.push(chunk);
  }

  const onAbort = (): void => {
    closed = true;
    notify?.();
  };
  options.signal?.addEventListener("abort", onAbort);

  try {
    while (!closed || buffer.length > 0) {
      if (buffer.length === 0) {
        await new Promise<void>((resolve) => {
          notify = () => {
            notify = null;
            resolve();
          };
        });
        continue;
      }
      const chunk = buffer.shift()!;
      yield chunk;
      if (chunk.kind === "completed" || chunk.kind === "error") {
        return;
      }
    }
    if (closeError) {
      throw closeError;
    }
  } finally {
    task.subscribers.delete(subscriber);
    options.signal?.removeEventListener("abort", onAbort);
  }
}

export function getTaskStatus(taskContextId: string): {
  status: TaskStatus | "unknown";
  usedModel?: string;
  nextChunkId?: number;
  error?: string;
} {
  const task = activeTasks.get(taskContextId);
  if (!task) {
    return { status: "unknown" };
  }
  return {
    status: task.status,
    usedModel: task.usedModel,
    nextChunkId: task.nextChunkId,
    error: task.error
  };
}
